# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MaskRCNN.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(843, 633)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.train_btn = QtWidgets.QPushButton(self.centralwidget)
        self.train_btn.setGeometry(QtCore.QRect(50, 200, 281, 51))
        self.train_btn.setObjectName("train_btn")
        self.conf_rate = QtWidgets.QTextEdit(self.centralwidget)
        self.conf_rate.setGeometry(QtCore.QRect(150, 40, 161, 31))
        self.conf_rate.setObjectName("conf_rate")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 40, 121, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 111, 31))
        self.label_2.setObjectName("label_2")
        self.epochs = QtWidgets.QTextEdit(self.centralwidget)
        self.epochs.setGeometry(QtCore.QRect(150, 80, 161, 31))
        self.epochs.setObjectName("epochs")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(50, 150, 721, 41))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.upload_sets = QtWidgets.QPushButton(self.centralwidget)
        self.upload_sets.setGeometry(QtCore.QRect(340, 40, 131, 31))
        self.upload_sets.setObjectName("upload_sets")
        self.upload_weight = QtWidgets.QPushButton(self.centralwidget)
        self.upload_weight.setGeometry(QtCore.QRect(340, 80, 131, 31))
        self.upload_weight.setObjectName("upload_weight")
        self.upload_det = QtWidgets.QPushButton(self.centralwidget)
        self.upload_det.setGeometry(QtCore.QRect(480, 40, 171, 31))
        self.upload_det.setObjectName("upload_det")
        self.gpu_train = QtWidgets.QRadioButton(self.centralwidget)
        self.gpu_train.setGeometry(QtCore.QRect(660, 80, 115, 22))
        self.gpu_train.setObjectName("gpu_train")
        self.cpu_train = QtWidgets.QRadioButton(self.centralwidget)
        self.cpu_train.setGeometry(QtCore.QRect(660, 100, 115, 22))
        self.cpu_train.setObjectName("cpu_train")
        self.roi_convert = QtWidgets.QPushButton(self.centralwidget)
        self.roi_convert.setGeometry(QtCore.QRect(660, 40, 151, 31))
        self.roi_convert.setObjectName("roi_convert")
        self.detect_btn = QtWidgets.QPushButton(self.centralwidget)
        self.detect_btn.setGeometry(QtCore.QRect(490, 200, 281, 51))
        self.detect_btn.setObjectName("detect_btn")
        self.upload_det_2 = QtWidgets.QPushButton(self.centralwidget)
        self.upload_det_2.setGeometry(QtCore.QRect(480, 80, 171, 31))
        self.upload_det_2.setObjectName("upload_det_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 550, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 550, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(40, 250, 761, 281))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 759, 279))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textBrowser = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 761, 281))
        self.textBrowser.setObjectName("textBrowser")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 843, 28))
        self.menubar.setObjectName("menubar")
        self.menuMaskRCNN_Trainer = QtWidgets.QMenu(self.menubar)
        self.menuMaskRCNN_Trainer.setObjectName("menuMaskRCNN_Trainer")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionUpload_weights = QtWidgets.QAction(MainWindow)
        self.actionUpload_weights.setObjectName("actionUpload_weights")
        self.actionUpload_dataset = QtWidgets.QAction(MainWindow)
        self.actionUpload_dataset.setObjectName("actionUpload_dataset")
        self.actionConvert_ImageJ_ROIs = QtWidgets.QAction(MainWindow)
        self.actionConvert_ImageJ_ROIs.setObjectName("actionConvert_ImageJ_ROIs")
        self.menuMaskRCNN_Trainer.addAction(self.actionUpload_weights)
        self.menuMaskRCNN_Trainer.addAction(self.actionUpload_dataset)
        self.menuMaskRCNN_Trainer.addAction(self.actionConvert_ImageJ_ROIs)
        self.menubar.addAction(self.menuMaskRCNN_Trainer.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.train_btn.setText(_translate("MainWindow", "Train it!"))
        self.label.setText(_translate("MainWindow", "Confidence Rate: "))
        self.label_2.setText(_translate("MainWindow", "Traning Epochs: "))
        self.upload_sets.setText(_translate("MainWindow", "Upload datasets"))
        self.upload_weight.setText(_translate("MainWindow", "Upload weights"))
        self.upload_det.setText(_translate("MainWindow", "Upload detection images"))
        self.gpu_train.setText(_translate("MainWindow", "GPU Training"))
        self.cpu_train.setText(_translate("MainWindow", "CPU Training"))
        self.roi_convert.setText(_translate("MainWindow", "Convert ImageJ ROIs"))
        self.detect_btn.setText(_translate("MainWindow", "Detect it!"))
        self.upload_det_2.setText(_translate("MainWindow", "Open ImageJ results"))
        self.pushButton.setText(_translate("MainWindow", "Clear Log"))
        self.pushButton_2.setText(_translate("MainWindow", "Export Log"))
        self.menuMaskRCNN_Trainer.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionUpload_weights.setText(_translate("MainWindow", "Upload weights"))
        self.actionUpload_dataset.setText(_translate("MainWindow", "Upload dataset"))
        self.actionConvert_ImageJ_ROIs.setText(_translate("MainWindow", "Convert ImageJ ROIs"))

